version: '3.8'

services:
  mysqldb: 
    image: mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - mysqldb_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

volumes:
  mysqldb_data: